import { StyleSheet } from 'react-native';
import { color, space, type } from '../design/tokens';

export const drillStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: color.canvas },
  header: {
    paddingHorizontal: space.l,
    paddingTop: space.s,
    paddingBottom: 0,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: color.hairline,
  },
  bc: { ...type.micro, color: color.textTertiary, letterSpacing: 0.4 },
  bcAccent: { color: color.accent },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: space.s,
    marginTop: 4,
    marginBottom: space.s,
  },
  swat: { width: 9, height: 9, borderRadius: 2 },
  title: { ...type.title, color: color.textPrimary },
  accentLine: { height: 2, marginHorizontal: -space.l },
  body: { flex: 1 },
  bodyContent: { paddingHorizontal: space.l, paddingBottom: space.xxl },
  morphContainer: { paddingTop: space.m },
  sliceLabel: { ...type.micro, color: color.textPrimary, fontWeight: '500', letterSpacing: 0.3 },
  sliceMeta: { ...type.micro, color: color.textTertiary, fontWeight: '400' },
  sliceBars: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    height: 100,
    gap: 6,
    paddingBottom: space.xs,
    paddingTop: space.m,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: color.hairline,
  },
  barCol: { flex: 1, alignItems: 'center', justifyContent: 'flex-end', gap: 4 },
  bar: { width: '80%', borderRadius: 2, minHeight: 2 },
  barLabel: { ...type.micro, color: color.textTertiary, fontSize: 9 },
  tableHeader: {
    flexDirection: 'row',
    paddingTop: space.m,
    paddingBottom: space.s,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: color.hairline,
    gap: space.s,
  },
  thCode: { width: 52, ...type.micro, color: color.textTertiary, letterSpacing: 0.3 },
  thDesc: { flex: 1, ...type.micro, color: color.textTertiary, letterSpacing: 0.3 },
  thClaims: { width: 44, ...type.micro, color: color.textTertiary, letterSpacing: 0.3, textAlign: 'right' },
  thDenied: { width: 60, ...type.micro, color: color.textTertiary, letterSpacing: 0.3, textAlign: 'right' },
  tableRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    paddingVertical: space.s + 2,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: color.hairline,
    gap: space.s,
  },
  tdCode: {
    width: 52,
    ...type.caption,
    color: color.textPrimary,
    fontVariant: ['tabular-nums'],
    letterSpacing: 0.05,
  },
  tdDesc: {
    flex: 1,
    ...type.micro,
    fontWeight: '500',
    letterSpacing: 0.12,
    color: color.textTertiary,
    textTransform: 'uppercase',
  },
  tdClaims: {
    width: 44,
    ...type.caption,
    color: color.textSecondary,
    textAlign: 'right',
    fontVariant: ['tabular-nums'],
  },
  tdDenied: {
    width: 60,
    ...type.caption,
    color: color.textPrimary,
    textAlign: 'right',
    fontVariant: ['tabular-nums'],
  },
  tableTotal: {
    flexDirection: 'row',
    alignItems: 'baseline',
    paddingVertical: space.s + 2,
    gap: space.s,
  },
  tdTotalLabel: {
    flex: 1,
    ...type.micro,
    fontWeight: '500',
    letterSpacing: 0.3,
    color: color.textTertiary,
    textTransform: 'uppercase',
  },
  tdTotalClaims: {
    width: 44,
    ...type.caption,
    color: color.textPrimary,
    textAlign: 'right',
    fontVariant: ['tabular-nums'],
  },
  tdTotalDenied: {
    width: 60,
    ...type.caption,
    color: color.textPrimary,
    textAlign: 'right',
    fontVariant: ['tabular-nums'],
  },
  drillFoot: {
    paddingVertical: space.s,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: color.hairline,
    marginTop: space.xs,
  },
  drillFootText: { ...type.micro, color: color.textTertiary, letterSpacing: 0.3 },
  footer: { paddingTop: space.xl, alignItems: 'center' },
  footerText: { ...type.micro, color: color.textTertiary, letterSpacing: 0.4 },
});
